version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 9
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
